typography_spectrum: 0.16130342823453248
color:
  brandStrength: 0.26378164533525705
  lightness: 0.974101452389732
  saturation: 0.9256441371981055
  rhythmicContrast: 0.6278755646198988
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
layout_spectrum: 0.04688383894972503
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/71936d8d-6aac-463a-ac04-8cf6a4e4212f.jpg
name: Vaitsa Schools
navigation:
  - name: PROFILE – Ποιοι είμαστε
    id: 81cacad3-edb8-45a3-b76b-82a408371432
    type: content
  - name: 'Κανονισμός λειτουργίας '
    id: 99b052d6-cd4a-47dc-9690-00ee1dd64f26
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/629a6e82-7200-4b76-86ed-44bda7bcc89d.jpg
title: Το όνομα της επιτυχίας
description: Ξένες Γλώσσες για μαθητές και ενήλικες
